<script setup>

</script>

<template>
    <v-card>
        <v-card-title class="bg-grey-darken-3 text-center">
            KẾT QUẢ ĐÁNH GIÁ DANH HIỆU VĂN HOÁ
        </v-card-title>
        <v-table>
            <thead>
            <tr>
                <th rowspan="2">Năm</th>
                <th colspan="3">Xã, Phường, Thị trấn tiêu biểu</th>
                <th colspan="3">Khóm, Ấp văn hóa</th>
            </tr>
            <tr>
                <th>Tổng số</th>
                <th>Đạt chuẩn</th>
                <th>Tỉ lệ</th>
                <th>Tổng số</th>
                <th>Đạt chuẩn</th>
                <th>Tỉ lệ</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>2023</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2022</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2021</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2020</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2019</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2018</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>100%</td>
            </tr>
            <tr>
                <td>2017</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>94.59%</td>
            </tr>
            <tr>
                <td>2016</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>37</td>
                <td>86.49%</td>
            </tr>
            <tr>
                <td>2015</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>25</td>
                <td>86.49%</td>
            </tr>
            <tr>
                <td>2014</td>
                <td>9</td>
                <td>9</td>
                <td>100%</td>
                <td>37</td>
                <td>32</td>
                <td>75.68%</td>
            </tr>
            <tr>
                <td>2013</td>
                <td>9</td>
                <td>4</td>
                <td>44.44%</td>
                <td>37</td>
                <td>32</td>
                <td>72.97%</td>
            </tr>
            <tr>
                <td>2012</td>
                <td>9</td>
                <td>3</td>
                <td>33.33%</td>
                <td>37</td>
                <td>28</td>
                <td>75.68%</td>
            </tr>
            <tr>
                <td>2011</td>
                <td>9</td>
                <td>4</td>
                <td>44.44%</td>
                <td>37</td>
                <td>27</td>
                <td>72.97%</td>
            </tr>
            <tr>
                <td>2010</td>
                <td>9</td>
                <td>3</td>
                <td>33.33%</td>
                <td>37</td>
                <td>28</td>
                <td>75.68%</td>
            </tr>
            <tr>
                <td>2009</td>
                <td>9</td>
                <td>5</td>
                <td>55.56%</td>
                <td>37</td>
                <td>25</td>
                <td>67.57%</td>
            </tr>
            <tr>
                <td>2008</td>
                <td>9</td>
                <td>3</td>
                <td>33.33%</td>
                <td>37</td>
                <td>19</td>
                <td>51.35%</td>
            </tr>
            <tr>
                <td>2007</td>
                <td>9</td>
                <td>1</td>
                <td>11.11%</td>
                <td>37</td>
                <td>17</td>
                <td>45.95%</td>
            </tr>
            <tr>
                <td>2006</td>
                <td>9</td>
                <td>3</td>
                <td>33.33%</td>
                <td>37</td>
                <td>29</td>
                <td>78.38%</td>
            </tr>
            <tr>
                <td>2005</td>
                <td>9</td>
                <td>2</td>
                <td>22.22%</td>
                <td>34</td>
                <td>13</td>
                <td>38.24%</td>
            </tr>
            <tr>
                <td>2004</td>
                <td>8</td>
                <td>2</td>
                <td>25%</td>
                <td>33</td>
                <td>19</td>
                <td>57.58%</td>
            </tr>
            <tr>
                <td>2003</td>
                <td>8</td>
                <td>2</td>
                <td>25%</td>
                <td>33</td>
                <td>14</td>
                <td>42.42%</td>
            </tr>
            <tr>
                <td>2002</td>
                <td>8</td>
                <td>2</td>
                <td>25%</td>
                <td>33</td>
                <td>12</td>
                <td>36.36%</td>
            </tr>
            <tr>
                <td>2001</td>
                <td>8</td>
                <td>3</td>
                <td>37.5%</td>
                <td>33</td>
                <td>22</td>
                <td>66.67%</td>
            </tr>
            <tr>
                <td>2000</td>
                <td>8</td>
                <td>2</td>
                <td>25%</td>
                <td>33</td>
                <td>18</td>
                <td>54.55%</td>
            </tr>
            </tbody>
        </v-table>
    </v-card>
</template>

<style scoped>

</style>
